name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Authenticate with DockerHub using access token
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u sadademba --password-stdin

      # Build and push frontend image
      - name: Build and push frontend image
        run: |
          docker build -t frontend ./front-end-react
          docker tag frontend sadademba/project-cicd-2024:frontend-${GITHUB_RUN_ID}
          docker push sadademba/project-cicd-2024:frontend-${GITHUB_RUN_ID}

      # Build and push order-service image
      - name: Build and push order-service image
        run: |
          docker build -t order-service ./order-service
          docker tag order-service sadademba/project-cicd-2024:order-service-${GITHUB_RUN_ID}
          docker push sadademba/project-cicd-2024:order-service-${GITHUB_RUN_ID}

      # Build and push user-service image
      - name: Build and push user-service image
        run: |
          docker build -t user-service ./user-service
          docker tag user-service sadademba/project-cicd-2024:user-service-${GITHUB_RUN_ID}
          docker push sadademba/project-cicd-2024:user-service-${GITHUB_RUN_ID}
